### ISSUE TITLE
Opening speaker detail page which has a title including japanese characters in a new tab shows 404

### ISSUE THREAD

**Issue by sapphi-red** [jsconfjp/jsconf.jp#172]
I have encountered a bug.
Maybe it's an upstream issue.

### Steps to reproduce

1. Open https://jsconf.jp/2021/speakers/ .
1. Make sure service worker is activated and is running.
1. Open any speaker detail page in a new tab by middle click or ctrl+left click. The page must be opened for the first time. Also the page must include a character which has to be url-escaped (like japanese characters). For example, <https://jsconf.jp/2021/talk/webフロントエンドのリプレースを支えるテストの考え方>.
1. 404 page is shown. Seems like the url is broken (https://jsconf.jp/2021/talk/web%C3%A3%C2%83%C2%95%C3%A3%C2%83%C2%AD%C3%A3%C2%83%C2%B3%C3%A3%C2%83%C2%88%C3%A3%C2%82%C2%A8%C3%A3%C2%83%C2%B3%C3%A3%C2%83%C2%89%C3%A3%C2%81%C2%AE%C3%A3%C2%83%C2%AA%C3%A3%C2%83%C2%97%C3%A3%C2%83%C2%AC%C3%A3%C2%83%C2%BC%C3%A3%C2%82%C2%B9%C3%A3%C2%82%C2%92%C3%A6%C2%94%C2%AF%C3%A3%C2%81%C2%88%C3%A3%C2%82%C2%8B%C3%A3%C2%83%C2%86%C3%A3%C2%82%C2%B9%C3%A3%C2%83%C2%88%C3%A3%C2%81%C2%AE%C3%A8%C2%80%C2%83%C3%A3%C2%81%C2%88%C3%A6%C2%96%C2%B9/).

**Comment by Leko** [comment]
@sapphi-red Sorry for late reply. We removed multi-byte characters from the URL and the problem was fixed. Thank you for reporting!
