### ISSUE TITLE
Venue - Accessibility section's Japanese translation

### ISSUE THREAD

**Issue by yamanoku** [jsconfjp/jsconf.jp#28]
Nice to meet you! What a wonderful site!
It might be still in the middle of translation, but I was curious, so I made an issue.

[![Screenshot from Gyazo](https://gyazo.com/827e719710a0bd90cfd42c11299697b3/raw)](https://gyazo.com/827e719710a0bd90cfd42c11299697b3)
https://jsconf.jp/2019/venue/

JSConf is a great conference with accessibility in mind.
I'm looking forward to JSConf JP :)

**Comment by martinheidegger** [comment]
Should be fixed in #29 - thank you for bringing this to notice.
