### ISSUE TITLE
Speakers photos should always be in the same ratio

### ISSUE THREAD

**Issue by martinheidegger** [jsconfjp/jsconf.jp#397]
Cropping is not good: 
<img width="837" alt="Screen Shot 2023-11-17 at 14 46 45" src="https://github.com/jsconfjp/jsconf.jp/assets/914122/03d0d067-8389-453a-90da-fa27a0cefaf1">

**Comment by SStan-prog** [comment]
https://github.com/jsconfjp/jsconf.jp/pull/483

**Old:**
<img width="766" alt="Screenshot 2024-11-07 at 8 27 24 PM" src="https://github.com/user-attachments/assets/9d9a6f5a-1888-49ab-82c7-592c4b77bfd1">

**New**
<img width="761" alt="Screenshot 2024-11-07 at 8 27 37 PM" src="https://github.com/user-attachments/assets/90b02c2f-ee5b-4ad1-a5c8-c1ec563466b6">

**Comment by martinheidegger** [comment]
fixed.
