### ISSUE TITLE
Hide sponsor section on landing page

### ISSUE THREAD

**Issue by martinheidegger** [jsconfjp/jsconf.jp#471]
Right now the landing page still shows the sponsor section, even though we have enough sponsors this year.
今年は十分なスポンサーがいるにもかかわらず、現時点ではランディング ページにはまだスポンサー セクションが表示されています。

<img width="1270" alt="Screenshot 2024-10-26 at 15 30 25" src="https://github.com/user-attachments/assets/aa133028-b503-43da-98da-3126f66e321f">

**Comment by ansh-saini** [comment]
Hi, I would like to work on this.
Should I just remove this section?

**Comment by martinheidegger** [comment]
The sponsorFormUrl is set here, and should preferably remain set.
https://github.com/jsconfjp/jsconf.jp/blob/2fc57e77e14d2ba21aecd1780b95216b721032f0/2024/gatsby-config.js#L11

for a reason that I don't understand it _should_ show the form link but for a reason I don't understand it shows it greyed out:

https://github.com/jsconfjp/jsconf.jp/blob/2fc57e77e14d2ba21aecd1780b95216b721032f0/2024/src/pages/index.tsx#L264

setting the `available` flag to "false" seems the easiest option to hide the button, but I think it would be good to have a "cutoff" date in the site config that hides the form button, even if a form is set after a given date (which can be in the past). This way we can next year specify a cut-off date after which it will be automatically removed.

**Comment by ansh-saini** [comment]
The reason for the disabled button is a hardcoded `false` value in the code.
https://github.com/jsconfjp/jsconf.jp/blob/2fc57e77e14d2ba21aecd1780b95216b721032f0/2024/src/pages/index.tsx#L266

The cutoff date seems like a pretty good thing to have. Should I make a new attribute for it in the site config or can I utilise the existing `cfpDeadline`?
https://github.com/jsconfjp/jsconf.jp/blob/2fc57e77e14d2ba21aecd1780b95216b721032f0/2024/gatsby-config.js#L14

**Comment by martinheidegger** [comment]
Oh, i didn't see the `false` statement. yeah, This probably should be a different logic.
The `cfpDeadline` is used for the Call for Proposals. Introducing a second property is better.
