### ISSUE TITLE
会場の地図をホームページに追加 (Add venue plan)

### ISSUE THREAD

**Issue by martinheidegger** [jsconfjp/jsconf.jp#485]
会場の中が結構わかりにくいですので、できれば地図まをホームページに載せた方が良いかと考えられます。一応 2D だと大丈夫かと思います。
@yosuke-furukawa さん、こちらの地図はそのままでも載せることが一つかと思いますが許可的にはどうですか？https://drive.google.com/drive/u/0/folders/1XqpB13ITpYfQVKR_yNS0n3u_9IhOYiVU

Since the conference venue is quite difficult to understand, I think it would be good to have a map on the homepage. For a start 2d should be fine.

**Comment by martinheidegger** [comment]
https://github.com/jsconfjp/jsconf.jp/issues/486#issuecomment-2467447914

**Comment by yosuke-furukawa** [comment]
@martinheidegger マーティンのやつのがいいと思う。僕のやつは現地で張り出すくらいにしよう
