### ISSUE TITLE
会場の情報を増やす

### ISSUE THREAD

**Issue by martinheidegger** [jsconfjp/jsconf.jp#486]
2019 年に会場の情報はより多く載せていた。→ https://jsconf.jp/2019/venue/  同じ情報を今の会場についても追加した方が良いかと思います。

In 2019 we had much more information about the conference venue. https://jsconf.jp/2019/venue/ It would be good if we had similar information for this year's event.

Google Map JSConf 2024→ https://www.google.com/maps/d/u/0/edit?hl=en&mid=1Jbvo6_SR5oIP3hDEbg03OiXVafGJQ7o&ll=35.66905133875735%2C139.755726&z=13

**Comment by martinheidegger** [comment]
地図の下書き
Draft for an illustration of the venue
![PXL_20241108_134514042~2](https://github.com/user-attachments/assets/ef152426-5624-4876-abe3-e0c6cc9ea9a2)

**Comment by martinheidegger** [comment]
まだ作業完了していませんが今まではそこまで進みました。

<img width="894" alt="Screenshot 2024-11-10 at 16 58 49" src="https://github.com/user-attachments/assets/0330f5b1-d75b-4170-81e2-087ac4fcad70">

(Inkscape で作業)
![jsconf2024-conference-room](https://github.com/user-attachments/assets/2a7c335c-63e2-4b79-915d-213ae05bea23)

**Comment by martinheidegger** [comment]
Version 1

<img width="569" alt="Screenshot 2024-11-11 at 3 26 24" src="https://github.com/user-attachments/assets/b7fea742-c201-4486-ab6a-7a537082f28c">

![jsconf2024-conference-room](https://github.com/user-attachments/assets/e3559f6a-e65c-457d-9666-e6ce93225614)

**Comment by yosuke-furukawa** [comment]
天才。

**Comment by martinheidegger** [comment]
Version 2 (細かい改善、シャツ情報追加)

<img width="728" alt="Screenshot 2024-11-11 at 16 45 17" src="https://github.com/user-attachments/assets/10d1d40d-b226-40e1-b128-4a192c6195b9">

[jsconf2024-conference-room.svg](https://github.com/user-attachments/assets/9a346064-d6fb-42a9-b064-b0944d16f25f)

**Comment by SStan-prog** [comment]
@martinheidegger https://github.com/jsconfjp/jsconf.jp/pull/510

**Comment by martinheidegger** [comment]
@SStan-prog  👍  I added a review about the map. Though that would be just Task #485 . For this Task the other information (surroundings, access route etc.) would still have merit.

**Comment by martinheidegger** [comment]
Follow up #513
