### ISSUE TITLE
Improve Speaker data

### ISSUE THREAD

**Issue by martinheidegger** [jsconfjp/jsconf.jp#488]
すでに使われているスピーカーデータの形はいくつかを対応しています：
Our speaker format supports quite a few things:

https://github.com/jsconfjp/jsconf.jp/blob/3f0c2c608a81ddbeea1761cfe38f869085389759/2024/src/data/speakers.yaml#L30-L45

- [ ] Biography の代わりにできればフィルドを利用する。It would be good to use the fields instead of putting the data in the description (ex. [link](https://github.com/jsconfjp/jsconf.jp/blob/3f0c2c608a81ddbeea1761cfe38f869085389759/2024/src/data/speakers.yaml#L561-L564) should be github/x fields)
- [ ] `nameReading` を利用する。ローマ字を漢字の名前だと良いと思いますし、できればカタカナを海外の名前に追加。Make use of `nameReading` for people with reading in their name. _(Having katakana for foreign names may be good too)_
- [ ] できれば伝記を翻訳。Translate the biographies (deepl?)

**Comment by Lenapunya** [comment]
Not really highlighted here, but some speaker content display could be fixed a little bit. For example, **Track A** (10:10 -10:20) 1st speaker's talk description (10:10 -10:20) could be displayed better. It is very hard to read, especially in English.

**Comment by martinheidegger** [comment]
@Lenapunya if you have an idea how to improve it, don't hesitate with a PR!
