### ISSUE TITLE
Improve visited link color

### ISSUE THREAD

**Issue by martinheidegger** [jsconfjp/jsconf.jp#491]
以前に見たページのリンク色を設定する。
Define a color that works well for visited links.

<img width="780" alt="Screenshot 2024-11-07 at 22 26 00" src="https://github.com/user-attachments/assets/97e0c69a-f535-4a91-8c54-54a44280eb26">

**Comment by SStan-prog** [comment]
Having a specific color for visited links feels unneeded to me for a site with relatively little content. 
Tried to improve the look overall for the footer links and breadcrumb links. 

https://github.com/jsconfjp/jsconf.jp/pull/495
