### ISSUE TITLE
Accessibility: Test the Website

### ISSUE THREAD

**Issue by martinheidegger** [jsconfjp/jsconf.jp#493]
現在のホームページは Accessibiliy をチェックしていないので、自動または手作業でチェックして Issue を追加のタスク。
The homepage currently hasn't been checked for Accessibility issues. Check the website for accessibility either by hand or with a script and add issues to this tracker.

**Comment by SStan-prog** [comment]
Still more work to do, but this fixes heading order, volunteer alt text, and the language switch

https://github.com/jsconfjp/jsconf.jp/pull/494

**Comment by martinheidegger** [comment]
@SStan-prog How did you test for Accessibility? (How do you identify the issues?)

**Comment by SStan-prog** [comment]
Using https://pagespeed.web.dev/
