### ISSUE TITLE
some talks bullet points are broken.

### ISSUE THREAD

**Issue by yosuke-furukawa** [jsconfjp/jsconf.jp#499]
![image](https://github.com/user-attachments/assets/d95d1037-5e2e-415e-9eff-8583ca0e2e6d)
![image](https://github.com/user-attachments/assets/22a67742-8d6d-4e6e-b648-57a43f9529ad)
![image](https://github.com/user-attachments/assets/1eb2a1a8-3c11-4255-94f6-e2eb470b91b1)

https://jsconf.jp/2024/talk/sosuke-suzuki/
https://jsconf.jp/2024/talk/mesut-durukal/
https://jsconf.jp/2024/talk/mizdra/

**Comment by martinheidegger** [comment]
Closed in #500
