### ISSUE TITLE
Fix Venue Map

### ISSUE THREAD

**Issue by martinheidegger** [jsconfjp/jsconf.jp#513]
- [ ] On Desktop (probably iPhone too) it shows the wrong font: 
<img width="589" alt="Screenshot 2024-11-20 at 16 54 57" src="https://github.com/user-attachments/assets/01fb5cd6-c5ea-4a97-96fb-48dbb24eeaa4">

- [ ] The labels can be translated to japanese.

cc. @SStan-prog

**Comment by SStan-prog** [comment]
@martinheidegger 
https://github.com/jsconfjp/jsconf.jp/pull/515
